apiVersion: apps/v1
kind: Deployment
metadata:
  name: generadorec-app
  namespace: generadorec
  labels:
    app: generadorec
    component: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: generadorec
      component: app
  template:
    metadata:
      labels:
        app: generadorec
        component: app
    spec:
      containers:
      - name: generadorec
        image: dmarmijosa/generadorec:v1.0.4
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: API_URL
          value: "https://generadorec.dmarmijosa.com/api"
        - name: CACHE_BUST
          value: "v1.0.4-20250801"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/generator/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/generator/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
      - name: dockerhub-secret
