apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: generadorec-ingress
  namespace: generadorec
  labels:
    app: generadorec
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  tls:
  - hosts:
    - generadorec.dmarmijosa.com
    secretName: generadorec-tls
  rules:
  - host: generadorec.dmarmijosa.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: generadorec-service
            port:
              number: 80
