apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: generadorec
  namespace: generadorec

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - poddisruptionbudget.yaml
  - hpa.yaml

commonLabels:
  app: generadorec
  version: v1.0.0
  managed-by: argocd

images:
  - name: dmarmijosa/generadorec
    newTag: latest

replicas:
  - name: generadorec-app
    count: 2
