apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: generadorec-pdb
  namespace: generadorec
  labels:
    app: generadorec
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: generadorec
      component: app
